import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const GCS_BUCKET = process.env.GCS_BUCKET_NAME || '';

const MODELS: Record<string, string> = {
  'nano-banana': 'gemini-2.0-flash-exp',
  'nano-banana-2': 'gemini-2.0-flash-exp',
  'nano-banana-pro': 'gemini-2.0-flash-exp',
};

export async function POST(request: NextRequest) {
  try {
    if (!GEMINI_API_KEY) {
      return NextResponse.json({ error: 'Gemini API key not configured' }, { status: 500 });
    }

    const { prompt, model = 'nano-banana', projectId, renderType } = await request.json();

    if (!prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 });
    }

    const modelId = MODELS[model] || MODELS['nano-banana'];
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${GEMINI_API_KEY}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          responseModalities: ['TEXT', 'IMAGE'],
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error:', errorText);
      return NextResponse.json(
        { error: 'Gemini API call failed', details: errorText },
        { status: response.status }
      );
    }

    const data = await response.json();

    // Extract image from response
    let imageBase64: string | null = null;
    let mimeType = 'image/png';

    if (data.candidates?.[0]?.content?.parts) {
      for (const part of data.candidates[0].content.parts) {
        if (part.inlineData?.data) {
          imageBase64 = part.inlineData.data;
          mimeType = part.inlineData.mimeType || 'image/png';
          break;
        }
      }
    }

    if (!imageBase64) {
      return NextResponse.json({ error: 'No image generated by AI' }, { status: 500 });
    }

    // Try GCS upload if configured, otherwise return base64 directly
    let publicUrl: string | null = null;

    if (GCS_BUCKET) {
      try {
        const { Storage } = await import('@google-cloud/storage');
        const storage = new Storage({ projectId: process.env.GCP_PROJECT_ID });
        const bucket = storage.bucket(GCS_BUCKET);
        const timestamp = Date.now();
        const ext = mimeType.includes('jpeg') ? 'jpg' : 'png';
        const filename = `renders/${projectId || 'anonymous'}/${renderType || 'render'}_${timestamp}.${ext}`;
        
        const file = bucket.file(filename);
        const buffer = Buffer.from(imageBase64, 'base64');
        
        await file.save(buffer, {
          contentType: mimeType,
          metadata: { cacheControl: 'public, max-age=31536000' },
        });

        await file.makePublic();
        publicUrl = `https://storage.googleapis.com/${GCS_BUCKET}/${filename}`;
      } catch (gcsErr: any) {
        console.warn('GCS upload failed, returning base64 instead:', gcsErr.message);
      }
    }

    // Return GCS URL if available, otherwise return base64 data URI
    const imageDataUri = `data:${mimeType};base64,${imageBase64}`;

    return NextResponse.json({
      success: true,
      imageUrl: publicUrl || null,
      imageDataUri,
      mimeType,
    });
  } catch (error: any) {
    console.error('Render generation error:', error);
    return NextResponse.json(
      { error: 'Internal server error', details: error.message },
      { status: 500 }
    );
  }
}
